(package "typepad"
         "0.2.1"
         "typepad in Emacs")

(website-url "https://github.com/welandx/TypePad.el")
(keywords "typing")

(package-file "typepad.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(files "typepad-time.el" "typepad-pyim.el"
       "buffer-focus-hook/buffer-focus-hook.el" "typepad.el"
       "typepad-lib.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "29.1")
(depends-on "pyim")
